### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by eisneim** [tokenfoundry/koa-react-ssr-example#2]
hi, great tutorial! but i have this error and don't know how to fix it, any help would be appreciated
```
TypeError: Object(...) is not a function
      at Module../pages/_document.js (?/build/server/static/development/pages/_document.js:161:71)
      at __webpack_require__ (?/build/server/static/development/pages/_document.js:23:31)
      at Object.1 (?/build/server/static/development/pages/_document.js:283:18)
      at __webpack_require__ (?/build/server/static/development/pages/_document.js:23:31)
      at ?/build/server/static/development/pages/_document.js:91:18
      at Object.<anonymous> (?/build/server/static/development/pages/_document.js:94:10)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by eisneim** [comment]
solved, caused by:
```
injectGlobal`
  body {
    background-color: #fafafa;
    margin: 0;
    padding: 0;
  }
`;
```
